// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YanoData.proto

package yanomonitor;

public final class YanoData {
  private YanoData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DatasOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Anon anons = 1;
    /**
     * <code>repeated .Anon anons = 1;</code>
     */
    java.util.List<yanomonitor.YanoData.Anon> 
        getAnonsList();
    /**
     * <code>repeated .Anon anons = 1;</code>
     */
    yanomonitor.YanoData.Anon getAnons(int index);
    /**
     * <code>repeated .Anon anons = 1;</code>
     */
    int getAnonsCount();
    /**
     * <code>repeated .Anon anons = 1;</code>
     */
    java.util.List<? extends yanomonitor.YanoData.AnonOrBuilder> 
        getAnonsOrBuilderList();
    /**
     * <code>repeated .Anon anons = 1;</code>
     */
    yanomonitor.YanoData.AnonOrBuilder getAnonsOrBuilder(
        int index);

    // repeated .Relations relations = 2;
    /**
     * <code>repeated .Relations relations = 2;</code>
     */
    java.util.List<yanomonitor.YanoData.Relations> 
        getRelationsList();
    /**
     * <code>repeated .Relations relations = 2;</code>
     */
    yanomonitor.YanoData.Relations getRelations(int index);
    /**
     * <code>repeated .Relations relations = 2;</code>
     */
    int getRelationsCount();
    /**
     * <code>repeated .Relations relations = 2;</code>
     */
    java.util.List<? extends yanomonitor.YanoData.RelationsOrBuilder> 
        getRelationsOrBuilderList();
    /**
     * <code>repeated .Relations relations = 2;</code>
     */
    yanomonitor.YanoData.RelationsOrBuilder getRelationsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Datas}
   */
  public static final class Datas extends
      com.google.protobuf.GeneratedMessage
      implements DatasOrBuilder {
    // Use Datas.newBuilder() to construct.
    private Datas(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Datas(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Datas defaultInstance;
    public static Datas getDefaultInstance() {
      return defaultInstance;
    }

    public Datas getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Datas(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                anons_ = new java.util.ArrayList<yanomonitor.YanoData.Anon>();
                mutable_bitField0_ |= 0x00000001;
              }
              anons_.add(input.readMessage(yanomonitor.YanoData.Anon.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                relations_ = new java.util.ArrayList<yanomonitor.YanoData.Relations>();
                mutable_bitField0_ |= 0x00000002;
              }
              relations_.add(input.readMessage(yanomonitor.YanoData.Relations.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          anons_ = java.util.Collections.unmodifiableList(anons_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          relations_ = java.util.Collections.unmodifiableList(relations_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yanomonitor.YanoData.internal_static_Datas_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yanomonitor.YanoData.internal_static_Datas_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yanomonitor.YanoData.Datas.class, yanomonitor.YanoData.Datas.Builder.class);
    }

    public static com.google.protobuf.Parser<Datas> PARSER =
        new com.google.protobuf.AbstractParser<Datas>() {
      public Datas parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Datas(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Datas> getParserForType() {
      return PARSER;
    }

    // repeated .Anon anons = 1;
    public static final int ANONS_FIELD_NUMBER = 1;
    private java.util.List<yanomonitor.YanoData.Anon> anons_;
    /**
     * <code>repeated .Anon anons = 1;</code>
     */
    public java.util.List<yanomonitor.YanoData.Anon> getAnonsList() {
      return anons_;
    }
    /**
     * <code>repeated .Anon anons = 1;</code>
     */
    public java.util.List<? extends yanomonitor.YanoData.AnonOrBuilder> 
        getAnonsOrBuilderList() {
      return anons_;
    }
    /**
     * <code>repeated .Anon anons = 1;</code>
     */
    public int getAnonsCount() {
      return anons_.size();
    }
    /**
     * <code>repeated .Anon anons = 1;</code>
     */
    public yanomonitor.YanoData.Anon getAnons(int index) {
      return anons_.get(index);
    }
    /**
     * <code>repeated .Anon anons = 1;</code>
     */
    public yanomonitor.YanoData.AnonOrBuilder getAnonsOrBuilder(
        int index) {
      return anons_.get(index);
    }

    // repeated .Relations relations = 2;
    public static final int RELATIONS_FIELD_NUMBER = 2;
    private java.util.List<yanomonitor.YanoData.Relations> relations_;
    /**
     * <code>repeated .Relations relations = 2;</code>
     */
    public java.util.List<yanomonitor.YanoData.Relations> getRelationsList() {
      return relations_;
    }
    /**
     * <code>repeated .Relations relations = 2;</code>
     */
    public java.util.List<? extends yanomonitor.YanoData.RelationsOrBuilder> 
        getRelationsOrBuilderList() {
      return relations_;
    }
    /**
     * <code>repeated .Relations relations = 2;</code>
     */
    public int getRelationsCount() {
      return relations_.size();
    }
    /**
     * <code>repeated .Relations relations = 2;</code>
     */
    public yanomonitor.YanoData.Relations getRelations(int index) {
      return relations_.get(index);
    }
    /**
     * <code>repeated .Relations relations = 2;</code>
     */
    public yanomonitor.YanoData.RelationsOrBuilder getRelationsOrBuilder(
        int index) {
      return relations_.get(index);
    }

    private void initFields() {
      anons_ = java.util.Collections.emptyList();
      relations_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getAnonsCount(); i++) {
        if (!getAnons(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getRelationsCount(); i++) {
        if (!getRelations(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < anons_.size(); i++) {
        output.writeMessage(1, anons_.get(i));
      }
      for (int i = 0; i < relations_.size(); i++) {
        output.writeMessage(2, relations_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < anons_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, anons_.get(i));
      }
      for (int i = 0; i < relations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, relations_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static yanomonitor.YanoData.Datas parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yanomonitor.YanoData.Datas parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yanomonitor.YanoData.Datas parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yanomonitor.YanoData.Datas parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yanomonitor.YanoData.Datas parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yanomonitor.YanoData.Datas parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static yanomonitor.YanoData.Datas parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static yanomonitor.YanoData.Datas parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static yanomonitor.YanoData.Datas parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yanomonitor.YanoData.Datas parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(yanomonitor.YanoData.Datas prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Datas}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements yanomonitor.YanoData.DatasOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yanomonitor.YanoData.internal_static_Datas_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yanomonitor.YanoData.internal_static_Datas_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yanomonitor.YanoData.Datas.class, yanomonitor.YanoData.Datas.Builder.class);
      }

      // Construct using yanomonitor.YanoData.Datas.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAnonsFieldBuilder();
          getRelationsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (anonsBuilder_ == null) {
          anons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          anonsBuilder_.clear();
        }
        if (relationsBuilder_ == null) {
          relations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          relationsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yanomonitor.YanoData.internal_static_Datas_descriptor;
      }

      public yanomonitor.YanoData.Datas getDefaultInstanceForType() {
        return yanomonitor.YanoData.Datas.getDefaultInstance();
      }

      public yanomonitor.YanoData.Datas build() {
        yanomonitor.YanoData.Datas result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public yanomonitor.YanoData.Datas buildPartial() {
        yanomonitor.YanoData.Datas result = new yanomonitor.YanoData.Datas(this);
        int from_bitField0_ = bitField0_;
        if (anonsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            anons_ = java.util.Collections.unmodifiableList(anons_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.anons_ = anons_;
        } else {
          result.anons_ = anonsBuilder_.build();
        }
        if (relationsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            relations_ = java.util.Collections.unmodifiableList(relations_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.relations_ = relations_;
        } else {
          result.relations_ = relationsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yanomonitor.YanoData.Datas) {
          return mergeFrom((yanomonitor.YanoData.Datas)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yanomonitor.YanoData.Datas other) {
        if (other == yanomonitor.YanoData.Datas.getDefaultInstance()) return this;
        if (anonsBuilder_ == null) {
          if (!other.anons_.isEmpty()) {
            if (anons_.isEmpty()) {
              anons_ = other.anons_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAnonsIsMutable();
              anons_.addAll(other.anons_);
            }
            onChanged();
          }
        } else {
          if (!other.anons_.isEmpty()) {
            if (anonsBuilder_.isEmpty()) {
              anonsBuilder_.dispose();
              anonsBuilder_ = null;
              anons_ = other.anons_;
              bitField0_ = (bitField0_ & ~0x00000001);
              anonsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAnonsFieldBuilder() : null;
            } else {
              anonsBuilder_.addAllMessages(other.anons_);
            }
          }
        }
        if (relationsBuilder_ == null) {
          if (!other.relations_.isEmpty()) {
            if (relations_.isEmpty()) {
              relations_ = other.relations_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRelationsIsMutable();
              relations_.addAll(other.relations_);
            }
            onChanged();
          }
        } else {
          if (!other.relations_.isEmpty()) {
            if (relationsBuilder_.isEmpty()) {
              relationsBuilder_.dispose();
              relationsBuilder_ = null;
              relations_ = other.relations_;
              bitField0_ = (bitField0_ & ~0x00000002);
              relationsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRelationsFieldBuilder() : null;
            } else {
              relationsBuilder_.addAllMessages(other.relations_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getAnonsCount(); i++) {
          if (!getAnons(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getRelationsCount(); i++) {
          if (!getRelations(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yanomonitor.YanoData.Datas parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yanomonitor.YanoData.Datas) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Anon anons = 1;
      private java.util.List<yanomonitor.YanoData.Anon> anons_ =
        java.util.Collections.emptyList();
      private void ensureAnonsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          anons_ = new java.util.ArrayList<yanomonitor.YanoData.Anon>(anons_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          yanomonitor.YanoData.Anon, yanomonitor.YanoData.Anon.Builder, yanomonitor.YanoData.AnonOrBuilder> anonsBuilder_;

      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public java.util.List<yanomonitor.YanoData.Anon> getAnonsList() {
        if (anonsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(anons_);
        } else {
          return anonsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public int getAnonsCount() {
        if (anonsBuilder_ == null) {
          return anons_.size();
        } else {
          return anonsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public yanomonitor.YanoData.Anon getAnons(int index) {
        if (anonsBuilder_ == null) {
          return anons_.get(index);
        } else {
          return anonsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public Builder setAnons(
          int index, yanomonitor.YanoData.Anon value) {
        if (anonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnonsIsMutable();
          anons_.set(index, value);
          onChanged();
        } else {
          anonsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public Builder setAnons(
          int index, yanomonitor.YanoData.Anon.Builder builderForValue) {
        if (anonsBuilder_ == null) {
          ensureAnonsIsMutable();
          anons_.set(index, builderForValue.build());
          onChanged();
        } else {
          anonsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public Builder addAnons(yanomonitor.YanoData.Anon value) {
        if (anonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnonsIsMutable();
          anons_.add(value);
          onChanged();
        } else {
          anonsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public Builder addAnons(
          int index, yanomonitor.YanoData.Anon value) {
        if (anonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnonsIsMutable();
          anons_.add(index, value);
          onChanged();
        } else {
          anonsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public Builder addAnons(
          yanomonitor.YanoData.Anon.Builder builderForValue) {
        if (anonsBuilder_ == null) {
          ensureAnonsIsMutable();
          anons_.add(builderForValue.build());
          onChanged();
        } else {
          anonsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public Builder addAnons(
          int index, yanomonitor.YanoData.Anon.Builder builderForValue) {
        if (anonsBuilder_ == null) {
          ensureAnonsIsMutable();
          anons_.add(index, builderForValue.build());
          onChanged();
        } else {
          anonsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public Builder addAllAnons(
          java.lang.Iterable<? extends yanomonitor.YanoData.Anon> values) {
        if (anonsBuilder_ == null) {
          ensureAnonsIsMutable();
          super.addAll(values, anons_);
          onChanged();
        } else {
          anonsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public Builder clearAnons() {
        if (anonsBuilder_ == null) {
          anons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          anonsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public Builder removeAnons(int index) {
        if (anonsBuilder_ == null) {
          ensureAnonsIsMutable();
          anons_.remove(index);
          onChanged();
        } else {
          anonsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public yanomonitor.YanoData.Anon.Builder getAnonsBuilder(
          int index) {
        return getAnonsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public yanomonitor.YanoData.AnonOrBuilder getAnonsOrBuilder(
          int index) {
        if (anonsBuilder_ == null) {
          return anons_.get(index);  } else {
          return anonsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public java.util.List<? extends yanomonitor.YanoData.AnonOrBuilder> 
           getAnonsOrBuilderList() {
        if (anonsBuilder_ != null) {
          return anonsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(anons_);
        }
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public yanomonitor.YanoData.Anon.Builder addAnonsBuilder() {
        return getAnonsFieldBuilder().addBuilder(
            yanomonitor.YanoData.Anon.getDefaultInstance());
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public yanomonitor.YanoData.Anon.Builder addAnonsBuilder(
          int index) {
        return getAnonsFieldBuilder().addBuilder(
            index, yanomonitor.YanoData.Anon.getDefaultInstance());
      }
      /**
       * <code>repeated .Anon anons = 1;</code>
       */
      public java.util.List<yanomonitor.YanoData.Anon.Builder> 
           getAnonsBuilderList() {
        return getAnonsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          yanomonitor.YanoData.Anon, yanomonitor.YanoData.Anon.Builder, yanomonitor.YanoData.AnonOrBuilder> 
          getAnonsFieldBuilder() {
        if (anonsBuilder_ == null) {
          anonsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              yanomonitor.YanoData.Anon, yanomonitor.YanoData.Anon.Builder, yanomonitor.YanoData.AnonOrBuilder>(
                  anons_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          anons_ = null;
        }
        return anonsBuilder_;
      }

      // repeated .Relations relations = 2;
      private java.util.List<yanomonitor.YanoData.Relations> relations_ =
        java.util.Collections.emptyList();
      private void ensureRelationsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          relations_ = new java.util.ArrayList<yanomonitor.YanoData.Relations>(relations_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          yanomonitor.YanoData.Relations, yanomonitor.YanoData.Relations.Builder, yanomonitor.YanoData.RelationsOrBuilder> relationsBuilder_;

      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public java.util.List<yanomonitor.YanoData.Relations> getRelationsList() {
        if (relationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(relations_);
        } else {
          return relationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public int getRelationsCount() {
        if (relationsBuilder_ == null) {
          return relations_.size();
        } else {
          return relationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public yanomonitor.YanoData.Relations getRelations(int index) {
        if (relationsBuilder_ == null) {
          return relations_.get(index);
        } else {
          return relationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public Builder setRelations(
          int index, yanomonitor.YanoData.Relations value) {
        if (relationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelationsIsMutable();
          relations_.set(index, value);
          onChanged();
        } else {
          relationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public Builder setRelations(
          int index, yanomonitor.YanoData.Relations.Builder builderForValue) {
        if (relationsBuilder_ == null) {
          ensureRelationsIsMutable();
          relations_.set(index, builderForValue.build());
          onChanged();
        } else {
          relationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public Builder addRelations(yanomonitor.YanoData.Relations value) {
        if (relationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelationsIsMutable();
          relations_.add(value);
          onChanged();
        } else {
          relationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public Builder addRelations(
          int index, yanomonitor.YanoData.Relations value) {
        if (relationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelationsIsMutable();
          relations_.add(index, value);
          onChanged();
        } else {
          relationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public Builder addRelations(
          yanomonitor.YanoData.Relations.Builder builderForValue) {
        if (relationsBuilder_ == null) {
          ensureRelationsIsMutable();
          relations_.add(builderForValue.build());
          onChanged();
        } else {
          relationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public Builder addRelations(
          int index, yanomonitor.YanoData.Relations.Builder builderForValue) {
        if (relationsBuilder_ == null) {
          ensureRelationsIsMutable();
          relations_.add(index, builderForValue.build());
          onChanged();
        } else {
          relationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public Builder addAllRelations(
          java.lang.Iterable<? extends yanomonitor.YanoData.Relations> values) {
        if (relationsBuilder_ == null) {
          ensureRelationsIsMutable();
          super.addAll(values, relations_);
          onChanged();
        } else {
          relationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public Builder clearRelations() {
        if (relationsBuilder_ == null) {
          relations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          relationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public Builder removeRelations(int index) {
        if (relationsBuilder_ == null) {
          ensureRelationsIsMutable();
          relations_.remove(index);
          onChanged();
        } else {
          relationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public yanomonitor.YanoData.Relations.Builder getRelationsBuilder(
          int index) {
        return getRelationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public yanomonitor.YanoData.RelationsOrBuilder getRelationsOrBuilder(
          int index) {
        if (relationsBuilder_ == null) {
          return relations_.get(index);  } else {
          return relationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public java.util.List<? extends yanomonitor.YanoData.RelationsOrBuilder> 
           getRelationsOrBuilderList() {
        if (relationsBuilder_ != null) {
          return relationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(relations_);
        }
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public yanomonitor.YanoData.Relations.Builder addRelationsBuilder() {
        return getRelationsFieldBuilder().addBuilder(
            yanomonitor.YanoData.Relations.getDefaultInstance());
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public yanomonitor.YanoData.Relations.Builder addRelationsBuilder(
          int index) {
        return getRelationsFieldBuilder().addBuilder(
            index, yanomonitor.YanoData.Relations.getDefaultInstance());
      }
      /**
       * <code>repeated .Relations relations = 2;</code>
       */
      public java.util.List<yanomonitor.YanoData.Relations.Builder> 
           getRelationsBuilderList() {
        return getRelationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          yanomonitor.YanoData.Relations, yanomonitor.YanoData.Relations.Builder, yanomonitor.YanoData.RelationsOrBuilder> 
          getRelationsFieldBuilder() {
        if (relationsBuilder_ == null) {
          relationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              yanomonitor.YanoData.Relations, yanomonitor.YanoData.Relations.Builder, yanomonitor.YanoData.RelationsOrBuilder>(
                  relations_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          relations_ = null;
        }
        return relationsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Datas)
    }

    static {
      defaultInstance = new Datas(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Datas)
  }

  public interface AnonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool isMe = 1 [default = false];
    /**
     * <code>required bool isMe = 1 [default = false];</code>
     */
    boolean hasIsMe();
    /**
     * <code>required bool isMe = 1 [default = false];</code>
     */
    boolean getIsMe();

    // required float x = 2;
    /**
     * <code>required float x = 2;</code>
     */
    boolean hasX();
    /**
     * <code>required float x = 2;</code>
     */
    float getX();

    // required float y = 3;
    /**
     * <code>required float y = 3;</code>
     *
     * <pre>
     *required int32 id = 4;
     *optional int32 relId = 5;
     * </pre>
     */
    boolean hasY();
    /**
     * <code>required float y = 3;</code>
     *
     * <pre>
     *required int32 id = 4;
     *optional int32 relId = 5;
     * </pre>
     */
    float getY();

    // required .Anon.Name name = 6 [default = Party];
    /**
     * <code>required .Anon.Name name = 6 [default = Party];</code>
     */
    boolean hasName();
    /**
     * <code>required .Anon.Name name = 6 [default = Party];</code>
     */
    yanomonitor.YanoData.Anon.Name getName();
  }
  /**
   * Protobuf type {@code Anon}
   */
  public static final class Anon extends
      com.google.protobuf.GeneratedMessage
      implements AnonOrBuilder {
    // Use Anon.newBuilder() to construct.
    private Anon(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Anon(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Anon defaultInstance;
    public static Anon getDefaultInstance() {
      return defaultInstance;
    }

    public Anon getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Anon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isMe_ = input.readBool();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              x_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              y_ = input.readFloat();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              yanomonitor.YanoData.Anon.Name value = yanomonitor.YanoData.Anon.Name.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                name_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yanomonitor.YanoData.internal_static_Anon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yanomonitor.YanoData.internal_static_Anon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yanomonitor.YanoData.Anon.class, yanomonitor.YanoData.Anon.Builder.class);
    }

    public static com.google.protobuf.Parser<Anon> PARSER =
        new com.google.protobuf.AbstractParser<Anon>() {
      public Anon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Anon(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Anon> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Anon.Name}
     */
    public enum Name
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Party = 1;</code>
       */
      Party(0, 1),
      /**
       * <code>Fidesz = 2;</code>
       */
      Fidesz(1, 2),
      /**
       * <code>MSZP = 3;</code>
       */
      MSZP(2, 3),
      /**
       * <code>KDNP = 4;</code>
       */
      KDNP(3, 4),
      /**
       * <code>Jobbik = 5;</code>
       */
      Jobbik(4, 5),
      /**
       * <code>LMP = 6;</code>
       */
      LMP(5, 6),
      /**
       * <code>EgyuttPM = 7;</code>
       */
      EgyuttPM(6, 7),
      /**
       * <code>DK = 8;</code>
       */
      DK(7, 8),
      /**
       * <code>Yano = 9;</code>
       */
      Yano(8, 9),
      ;

      /**
       * <code>Party = 1;</code>
       */
      public static final int Party_VALUE = 1;
      /**
       * <code>Fidesz = 2;</code>
       */
      public static final int Fidesz_VALUE = 2;
      /**
       * <code>MSZP = 3;</code>
       */
      public static final int MSZP_VALUE = 3;
      /**
       * <code>KDNP = 4;</code>
       */
      public static final int KDNP_VALUE = 4;
      /**
       * <code>Jobbik = 5;</code>
       */
      public static final int Jobbik_VALUE = 5;
      /**
       * <code>LMP = 6;</code>
       */
      public static final int LMP_VALUE = 6;
      /**
       * <code>EgyuttPM = 7;</code>
       */
      public static final int EgyuttPM_VALUE = 7;
      /**
       * <code>DK = 8;</code>
       */
      public static final int DK_VALUE = 8;
      /**
       * <code>Yano = 9;</code>
       */
      public static final int Yano_VALUE = 9;


      public final int getNumber() { return value; }

      public static Name valueOf(int value) {
        switch (value) {
          case 1: return Party;
          case 2: return Fidesz;
          case 3: return MSZP;
          case 4: return KDNP;
          case 5: return Jobbik;
          case 6: return LMP;
          case 7: return EgyuttPM;
          case 8: return DK;
          case 9: return Yano;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Name>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Name>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Name>() {
              public Name findValueByNumber(int number) {
                return Name.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return yanomonitor.YanoData.Anon.getDescriptor().getEnumTypes().get(0);
      }

      private static final Name[] VALUES = values();

      public static Name valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Name(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Anon.Name)
    }

    private int bitField0_;
    // required bool isMe = 1 [default = false];
    public static final int ISME_FIELD_NUMBER = 1;
    private boolean isMe_;
    /**
     * <code>required bool isMe = 1 [default = false];</code>
     */
    public boolean hasIsMe() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool isMe = 1 [default = false];</code>
     */
    public boolean getIsMe() {
      return isMe_;
    }

    // required float x = 2;
    public static final int X_FIELD_NUMBER = 2;
    private float x_;
    /**
     * <code>required float x = 2;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float x = 2;</code>
     */
    public float getX() {
      return x_;
    }

    // required float y = 3;
    public static final int Y_FIELD_NUMBER = 3;
    private float y_;
    /**
     * <code>required float y = 3;</code>
     *
     * <pre>
     *required int32 id = 4;
     *optional int32 relId = 5;
     * </pre>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float y = 3;</code>
     *
     * <pre>
     *required int32 id = 4;
     *optional int32 relId = 5;
     * </pre>
     */
    public float getY() {
      return y_;
    }

    // required .Anon.Name name = 6 [default = Party];
    public static final int NAME_FIELD_NUMBER = 6;
    private yanomonitor.YanoData.Anon.Name name_;
    /**
     * <code>required .Anon.Name name = 6 [default = Party];</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .Anon.Name name = 6 [default = Party];</code>
     */
    public yanomonitor.YanoData.Anon.Name getName() {
      return name_;
    }

    private void initFields() {
      isMe_ = false;
      x_ = 0F;
      y_ = 0F;
      name_ = yanomonitor.YanoData.Anon.Name.Party;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIsMe()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isMe_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(6, name_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isMe_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, name_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static yanomonitor.YanoData.Anon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yanomonitor.YanoData.Anon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yanomonitor.YanoData.Anon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yanomonitor.YanoData.Anon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yanomonitor.YanoData.Anon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yanomonitor.YanoData.Anon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static yanomonitor.YanoData.Anon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static yanomonitor.YanoData.Anon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static yanomonitor.YanoData.Anon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yanomonitor.YanoData.Anon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(yanomonitor.YanoData.Anon prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Anon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements yanomonitor.YanoData.AnonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yanomonitor.YanoData.internal_static_Anon_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yanomonitor.YanoData.internal_static_Anon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yanomonitor.YanoData.Anon.class, yanomonitor.YanoData.Anon.Builder.class);
      }

      // Construct using yanomonitor.YanoData.Anon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isMe_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = yanomonitor.YanoData.Anon.Name.Party;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yanomonitor.YanoData.internal_static_Anon_descriptor;
      }

      public yanomonitor.YanoData.Anon getDefaultInstanceForType() {
        return yanomonitor.YanoData.Anon.getDefaultInstance();
      }

      public yanomonitor.YanoData.Anon build() {
        yanomonitor.YanoData.Anon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public yanomonitor.YanoData.Anon buildPartial() {
        yanomonitor.YanoData.Anon result = new yanomonitor.YanoData.Anon(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isMe_ = isMe_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yanomonitor.YanoData.Anon) {
          return mergeFrom((yanomonitor.YanoData.Anon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yanomonitor.YanoData.Anon other) {
        if (other == yanomonitor.YanoData.Anon.getDefaultInstance()) return this;
        if (other.hasIsMe()) {
          setIsMe(other.getIsMe());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsMe()) {
          
          return false;
        }
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yanomonitor.YanoData.Anon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yanomonitor.YanoData.Anon) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool isMe = 1 [default = false];
      private boolean isMe_ ;
      /**
       * <code>required bool isMe = 1 [default = false];</code>
       */
      public boolean hasIsMe() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool isMe = 1 [default = false];</code>
       */
      public boolean getIsMe() {
        return isMe_;
      }
      /**
       * <code>required bool isMe = 1 [default = false];</code>
       */
      public Builder setIsMe(boolean value) {
        bitField0_ |= 0x00000001;
        isMe_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isMe = 1 [default = false];</code>
       */
      public Builder clearIsMe() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isMe_ = false;
        onChanged();
        return this;
      }

      // required float x = 2;
      private float x_ ;
      /**
       * <code>required float x = 2;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float x = 2;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>required float x = 2;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x = 2;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0F;
        onChanged();
        return this;
      }

      // required float y = 3;
      private float y_ ;
      /**
       * <code>required float y = 3;</code>
       *
       * <pre>
       *required int32 id = 4;
       *optional int32 relId = 5;
       * </pre>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float y = 3;</code>
       *
       * <pre>
       *required int32 id = 4;
       *optional int32 relId = 5;
       * </pre>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>required float y = 3;</code>
       *
       * <pre>
       *required int32 id = 4;
       *optional int32 relId = 5;
       * </pre>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y = 3;</code>
       *
       * <pre>
       *required int32 id = 4;
       *optional int32 relId = 5;
       * </pre>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0F;
        onChanged();
        return this;
      }

      // required .Anon.Name name = 6 [default = Party];
      private yanomonitor.YanoData.Anon.Name name_ = yanomonitor.YanoData.Anon.Name.Party;
      /**
       * <code>required .Anon.Name name = 6 [default = Party];</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .Anon.Name name = 6 [default = Party];</code>
       */
      public yanomonitor.YanoData.Anon.Name getName() {
        return name_;
      }
      /**
       * <code>required .Anon.Name name = 6 [default = Party];</code>
       */
      public Builder setName(yanomonitor.YanoData.Anon.Name value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Anon.Name name = 6 [default = Party];</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = yanomonitor.YanoData.Anon.Name.Party;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Anon)
    }

    static {
      defaultInstance = new Anon(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Anon)
  }

  public interface RelationsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required float x1 = 1;
    /**
     * <code>required float x1 = 1;</code>
     */
    boolean hasX1();
    /**
     * <code>required float x1 = 1;</code>
     */
    float getX1();

    // required float y1 = 2;
    /**
     * <code>required float y1 = 2;</code>
     */
    boolean hasY1();
    /**
     * <code>required float y1 = 2;</code>
     */
    float getY1();

    // required float x2 = 3;
    /**
     * <code>required float x2 = 3;</code>
     */
    boolean hasX2();
    /**
     * <code>required float x2 = 3;</code>
     */
    float getX2();

    // required float y2 = 4;
    /**
     * <code>required float y2 = 4;</code>
     */
    boolean hasY2();
    /**
     * <code>required float y2 = 4;</code>
     */
    float getY2();

    // required .Relations.Name name = 5 [default = Family];
    /**
     * <code>required .Relations.Name name = 5 [default = Family];</code>
     */
    boolean hasName();
    /**
     * <code>required .Relations.Name name = 5 [default = Family];</code>
     */
    yanomonitor.YanoData.Relations.Name getName();
  }
  /**
   * Protobuf type {@code Relations}
   */
  public static final class Relations extends
      com.google.protobuf.GeneratedMessage
      implements RelationsOrBuilder {
    // Use Relations.newBuilder() to construct.
    private Relations(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Relations(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Relations defaultInstance;
    public static Relations getDefaultInstance() {
      return defaultInstance;
    }

    public Relations getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Relations(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              x1_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              y1_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              x2_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              y2_ = input.readFloat();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              yanomonitor.YanoData.Relations.Name value = yanomonitor.YanoData.Relations.Name.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                name_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yanomonitor.YanoData.internal_static_Relations_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yanomonitor.YanoData.internal_static_Relations_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yanomonitor.YanoData.Relations.class, yanomonitor.YanoData.Relations.Builder.class);
    }

    public static com.google.protobuf.Parser<Relations> PARSER =
        new com.google.protobuf.AbstractParser<Relations>() {
      public Relations parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Relations(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Relations> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Relations.Name}
     */
    public enum Name
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Family = 1;</code>
       */
      Family(0, 1),
      /**
       * <code>Mom = 2;</code>
       */
      Mom(1, 2),
      /**
       * <code>Dad = 3;</code>
       */
      Dad(2, 3),
      /**
       * <code>Sister = 4;</code>
       */
      Sister(3, 4),
      /**
       * <code>Brother = 5;</code>
       */
      Brother(4, 5),
      /**
       * <code>Wife = 6;</code>
       */
      Wife(5, 6),
      /**
       * <code>Husband = 7;</code>
       */
      Husband(6, 7),
      /**
       * <code>Daughter = 8;</code>
       */
      Daughter(7, 8),
      /**
       * <code>Son = 9;</code>
       */
      Son(8, 9),
      /**
       * <code>Grandma = 10;</code>
       */
      Grandma(9, 10),
      /**
       * <code>Grandpa = 11;</code>
       */
      Grandpa(10, 11),
      ;

      /**
       * <code>Family = 1;</code>
       */
      public static final int Family_VALUE = 1;
      /**
       * <code>Mom = 2;</code>
       */
      public static final int Mom_VALUE = 2;
      /**
       * <code>Dad = 3;</code>
       */
      public static final int Dad_VALUE = 3;
      /**
       * <code>Sister = 4;</code>
       */
      public static final int Sister_VALUE = 4;
      /**
       * <code>Brother = 5;</code>
       */
      public static final int Brother_VALUE = 5;
      /**
       * <code>Wife = 6;</code>
       */
      public static final int Wife_VALUE = 6;
      /**
       * <code>Husband = 7;</code>
       */
      public static final int Husband_VALUE = 7;
      /**
       * <code>Daughter = 8;</code>
       */
      public static final int Daughter_VALUE = 8;
      /**
       * <code>Son = 9;</code>
       */
      public static final int Son_VALUE = 9;
      /**
       * <code>Grandma = 10;</code>
       */
      public static final int Grandma_VALUE = 10;
      /**
       * <code>Grandpa = 11;</code>
       */
      public static final int Grandpa_VALUE = 11;


      public final int getNumber() { return value; }

      public static Name valueOf(int value) {
        switch (value) {
          case 1: return Family;
          case 2: return Mom;
          case 3: return Dad;
          case 4: return Sister;
          case 5: return Brother;
          case 6: return Wife;
          case 7: return Husband;
          case 8: return Daughter;
          case 9: return Son;
          case 10: return Grandma;
          case 11: return Grandpa;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Name>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Name>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Name>() {
              public Name findValueByNumber(int number) {
                return Name.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return yanomonitor.YanoData.Relations.getDescriptor().getEnumTypes().get(0);
      }

      private static final Name[] VALUES = values();

      public static Name valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Name(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Relations.Name)
    }

    private int bitField0_;
    // required float x1 = 1;
    public static final int X1_FIELD_NUMBER = 1;
    private float x1_;
    /**
     * <code>required float x1 = 1;</code>
     */
    public boolean hasX1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float x1 = 1;</code>
     */
    public float getX1() {
      return x1_;
    }

    // required float y1 = 2;
    public static final int Y1_FIELD_NUMBER = 2;
    private float y1_;
    /**
     * <code>required float y1 = 2;</code>
     */
    public boolean hasY1() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float y1 = 2;</code>
     */
    public float getY1() {
      return y1_;
    }

    // required float x2 = 3;
    public static final int X2_FIELD_NUMBER = 3;
    private float x2_;
    /**
     * <code>required float x2 = 3;</code>
     */
    public boolean hasX2() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float x2 = 3;</code>
     */
    public float getX2() {
      return x2_;
    }

    // required float y2 = 4;
    public static final int Y2_FIELD_NUMBER = 4;
    private float y2_;
    /**
     * <code>required float y2 = 4;</code>
     */
    public boolean hasY2() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float y2 = 4;</code>
     */
    public float getY2() {
      return y2_;
    }

    // required .Relations.Name name = 5 [default = Family];
    public static final int NAME_FIELD_NUMBER = 5;
    private yanomonitor.YanoData.Relations.Name name_;
    /**
     * <code>required .Relations.Name name = 5 [default = Family];</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .Relations.Name name = 5 [default = Family];</code>
     */
    public yanomonitor.YanoData.Relations.Name getName() {
      return name_;
    }

    private void initFields() {
      x1_ = 0F;
      y1_ = 0F;
      x2_ = 0F;
      y2_ = 0F;
      name_ = yanomonitor.YanoData.Relations.Name.Family;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasX1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, x1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, y1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, x2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, y2_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, name_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, x2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, y2_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, name_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static yanomonitor.YanoData.Relations parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yanomonitor.YanoData.Relations parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yanomonitor.YanoData.Relations parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yanomonitor.YanoData.Relations parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yanomonitor.YanoData.Relations parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yanomonitor.YanoData.Relations parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static yanomonitor.YanoData.Relations parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static yanomonitor.YanoData.Relations parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static yanomonitor.YanoData.Relations parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yanomonitor.YanoData.Relations parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(yanomonitor.YanoData.Relations prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Relations}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements yanomonitor.YanoData.RelationsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yanomonitor.YanoData.internal_static_Relations_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yanomonitor.YanoData.internal_static_Relations_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yanomonitor.YanoData.Relations.class, yanomonitor.YanoData.Relations.Builder.class);
      }

      // Construct using yanomonitor.YanoData.Relations.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x1_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        y1_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        x2_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        y2_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = yanomonitor.YanoData.Relations.Name.Family;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yanomonitor.YanoData.internal_static_Relations_descriptor;
      }

      public yanomonitor.YanoData.Relations getDefaultInstanceForType() {
        return yanomonitor.YanoData.Relations.getDefaultInstance();
      }

      public yanomonitor.YanoData.Relations build() {
        yanomonitor.YanoData.Relations result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public yanomonitor.YanoData.Relations buildPartial() {
        yanomonitor.YanoData.Relations result = new yanomonitor.YanoData.Relations(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x1_ = x1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y1_ = y1_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.x2_ = x2_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.y2_ = y2_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yanomonitor.YanoData.Relations) {
          return mergeFrom((yanomonitor.YanoData.Relations)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yanomonitor.YanoData.Relations other) {
        if (other == yanomonitor.YanoData.Relations.getDefaultInstance()) return this;
        if (other.hasX1()) {
          setX1(other.getX1());
        }
        if (other.hasY1()) {
          setY1(other.getY1());
        }
        if (other.hasX2()) {
          setX2(other.getX2());
        }
        if (other.hasY2()) {
          setY2(other.getY2());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX1()) {
          
          return false;
        }
        if (!hasY1()) {
          
          return false;
        }
        if (!hasX2()) {
          
          return false;
        }
        if (!hasY2()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yanomonitor.YanoData.Relations parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yanomonitor.YanoData.Relations) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required float x1 = 1;
      private float x1_ ;
      /**
       * <code>required float x1 = 1;</code>
       */
      public boolean hasX1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float x1 = 1;</code>
       */
      public float getX1() {
        return x1_;
      }
      /**
       * <code>required float x1 = 1;</code>
       */
      public Builder setX1(float value) {
        bitField0_ |= 0x00000001;
        x1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x1 = 1;</code>
       */
      public Builder clearX1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x1_ = 0F;
        onChanged();
        return this;
      }

      // required float y1 = 2;
      private float y1_ ;
      /**
       * <code>required float y1 = 2;</code>
       */
      public boolean hasY1() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float y1 = 2;</code>
       */
      public float getY1() {
        return y1_;
      }
      /**
       * <code>required float y1 = 2;</code>
       */
      public Builder setY1(float value) {
        bitField0_ |= 0x00000002;
        y1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y1 = 2;</code>
       */
      public Builder clearY1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y1_ = 0F;
        onChanged();
        return this;
      }

      // required float x2 = 3;
      private float x2_ ;
      /**
       * <code>required float x2 = 3;</code>
       */
      public boolean hasX2() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float x2 = 3;</code>
       */
      public float getX2() {
        return x2_;
      }
      /**
       * <code>required float x2 = 3;</code>
       */
      public Builder setX2(float value) {
        bitField0_ |= 0x00000004;
        x2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x2 = 3;</code>
       */
      public Builder clearX2() {
        bitField0_ = (bitField0_ & ~0x00000004);
        x2_ = 0F;
        onChanged();
        return this;
      }

      // required float y2 = 4;
      private float y2_ ;
      /**
       * <code>required float y2 = 4;</code>
       */
      public boolean hasY2() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float y2 = 4;</code>
       */
      public float getY2() {
        return y2_;
      }
      /**
       * <code>required float y2 = 4;</code>
       */
      public Builder setY2(float value) {
        bitField0_ |= 0x00000008;
        y2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y2 = 4;</code>
       */
      public Builder clearY2() {
        bitField0_ = (bitField0_ & ~0x00000008);
        y2_ = 0F;
        onChanged();
        return this;
      }

      // required .Relations.Name name = 5 [default = Family];
      private yanomonitor.YanoData.Relations.Name name_ = yanomonitor.YanoData.Relations.Name.Family;
      /**
       * <code>required .Relations.Name name = 5 [default = Family];</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .Relations.Name name = 5 [default = Family];</code>
       */
      public yanomonitor.YanoData.Relations.Name getName() {
        return name_;
      }
      /**
       * <code>required .Relations.Name name = 5 [default = Family];</code>
       */
      public Builder setName(yanomonitor.YanoData.Relations.Name value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Relations.Name name = 5 [default = Family];</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        name_ = yanomonitor.YanoData.Relations.Name.Family;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Relations)
    }

    static {
      defaultInstance = new Relations(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Relations)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Datas_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Datas_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Anon_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Anon_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Relations_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Relations_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016YanoData.proto\"<\n\005Datas\022\024\n\005anons\030\001 \003(\013" +
      "2\005.Anon\022\035\n\trelations\030\002 \003(\0132\n.Relations\"\272" +
      "\001\n\004Anon\022\023\n\004isMe\030\001 \002(\010:\005false\022\t\n\001x\030\002 \002(\002\022" +
      "\t\n\001y\030\003 \002(\002\022\037\n\004name\030\006 \002(\0162\n.Anon.Name:\005Pa" +
      "rty\"f\n\004Name\022\t\n\005Party\020\001\022\n\n\006Fidesz\020\002\022\010\n\004MS" +
      "ZP\020\003\022\010\n\004KDNP\020\004\022\n\n\006Jobbik\020\005\022\007\n\003LMP\020\006\022\014\n\010E" +
      "gyuttPM\020\007\022\006\n\002DK\020\010\022\010\n\004Yano\020\t\"\352\001\n\tRelation" +
      "s\022\n\n\002x1\030\001 \002(\002\022\n\n\002y1\030\002 \002(\002\022\n\n\002x2\030\003 \002(\002\022\n\n" +
      "\002y2\030\004 \002(\002\022%\n\004name\030\005 \002(\0162\017.Relations.Name" +
      ":\006Family\"\205\001\n\004Name\022\n\n\006Family\020\001\022\007\n\003Mom\020\002\022\007",
      "\n\003Dad\020\003\022\n\n\006Sister\020\004\022\013\n\007Brother\020\005\022\010\n\004Wife" +
      "\020\006\022\013\n\007Husband\020\007\022\014\n\010Daughter\020\010\022\007\n\003Son\020\t\022\013" +
      "\n\007Grandma\020\n\022\013\n\007Grandpa\020\013B\r\n\013yanomonitor"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Datas_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Datas_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Datas_descriptor,
              new java.lang.String[] { "Anons", "Relations", });
          internal_static_Anon_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Anon_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Anon_descriptor,
              new java.lang.String[] { "IsMe", "X", "Y", "Name", });
          internal_static_Relations_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Relations_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Relations_descriptor,
              new java.lang.String[] { "X1", "Y1", "X2", "Y2", "Name", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
